import type { AgentTool, AgentToolResult } from '@mariozechner/pi-agent-core'
import { Type, type Static } from '@sinclair/typebox'
import { readdirSync } from 'fs'
import { join } from 'path'
import { execFileSync } from 'child_process'
import type { ContainerRegistry } from '../../container/registry.js'

interface ListPatchesResult {
  patches: string[]
}

interface ApplyPatchesResult {
  applied: number
  failed: number
  conflicts: string[]
}

const ListPatchesSchema = Type.Object({
  containerId: Type.String({ description: 'Container ID' })
})

const ApplyPatchesSchema = Type.Object({
  patches: Type.Array(Type.String(), { description: 'Array of patch file paths' })
})

export function createListPatchesTool(registry: ContainerRegistry): AgentTool<typeof ListPatchesSchema> {
  return {
    name: 'list_patches',
    label: 'list_patches',
    description: 'List patches generated by container',
    parameters: ListPatchesSchema,
    execute: async (_id: string, args: Static<typeof ListPatchesSchema>): Promise<AgentToolResult<ListPatchesResult>> => {
      try {
        const container = registry.get(args.containerId)
        if (!container) {
          const result = { patches: [] }
          return {
            content: [{ type: 'text', text: JSON.stringify(result) }],
            details: result
          }
        }

        const runDir = container.metadata.runDir
        if (!runDir) {
          const result = { patches: [] }
          return {
            content: [{ type: 'text', text: JSON.stringify(result) }],
            details: result
          }
        }

        const patchesDir = join(runDir, 'patches')
        const files = readdirSync(patchesDir)
        const patches = files
          .filter(f => f.endsWith('.patch'))
          .map(f => join(patchesDir, f))
        const result = { patches }
        return {
          content: [{ type: 'text', text: JSON.stringify(result) }],
          details: result
        }
      } catch (error: any) {
        const result = { patches: [] }
        return {
          content: [{ type: 'text', text: JSON.stringify(result) }],
          details: result
        }
      }
    }
  }
}

export function createApplyPatchesTool(): AgentTool<typeof ApplyPatchesSchema> {
  return {
    name: 'apply_patches',
    label: 'apply_patches',
    description: 'Apply patches to local repository',
    parameters: ApplyPatchesSchema,
    execute: async (_id: string, args: Static<typeof ApplyPatchesSchema>): Promise<AgentToolResult<ApplyPatchesResult>> => {
      let applied = 0
      let failed = 0
      const conflicts: string[] = []

      for (const patch of args.patches) {
        try {
          execFileSync('git', ['am', patch], {
            stdio: 'pipe',
            cwd: process.cwd(),
            timeout: 60_000,
            maxBuffer: 1024 * 1024
          })
          applied++
        } catch (error) {
          failed++
          // Clean up failed git am operation
          try {
            execFileSync('git', ['am', '--abort'], { cwd: process.cwd() })
          } catch {
            // Ignore errors if there's nothing to abort
          }
          if (error instanceof Error && error.message.includes('conflict')) {
            conflicts.push(patch)
          }
        }
      }

      const result = { applied, failed, conflicts }
      return {
        content: [{ type: 'text', text: JSON.stringify(result) }],
        details: result
      }
    }
  }
}
