import { readdirSync } from 'fs'
import { join } from 'path'
import { execFileSync } from 'child_process'
import type { ContainerRegistry } from '../../container/registry.js'

interface ListPatchesArgs {
  containerId: string
}

interface ListPatchesResult {
  patches: string[]
}

interface ApplyPatchesArgs {
  patches: string[]
}

interface ApplyPatchesResult {
  applied: number
  failed: number
  conflicts: string[]
}

export function createListPatchesTool(registry: ContainerRegistry) {
  return {
    name: 'list_patches',
    description: 'List patches generated by container',
    parameters: {
      type: 'object',
      properties: {
        containerId: {
          type: 'string',
          description: 'Container ID'
        }
      },
      required: ['containerId']
    },
    execute: async (args: ListPatchesArgs): Promise<ListPatchesResult> => {
      try {
        const container = registry.get(args.containerId)
        if (!container) {
          return { patches: [] }
        }

        const runDir = container.metadata.runDir
        if (!runDir) {
          return { patches: [] }
        }

        const patchesDir = join(runDir, 'patches')
        const files = readdirSync(patchesDir)
        const patches = files
          .filter(f => f.endsWith('.patch'))
          .map(f => join(patchesDir, f))
        return { patches }
      } catch (error: any) {
        return { patches: [] }
      }
    }
  }
}

export function createApplyPatchesTool() {
  return {
    name: 'apply_patches',
    description: 'Apply patches to local repository',
    parameters: {
      type: 'object',
      properties: {
        patches: {
          type: 'array',
          items: { type: 'string' },
          description: 'Array of patch file paths'
        }
      },
      required: ['patches']
    },
    execute: async (args: ApplyPatchesArgs): Promise<ApplyPatchesResult> => {
      let applied = 0
      let failed = 0
      const conflicts: string[] = []

      for (const patch of args.patches) {
        try {
          execFileSync('git', ['am', patch], {
            stdio: 'pipe',
            cwd: process.cwd(),
            timeout: 60_000,
            maxBuffer: 1024 * 1024
          })
          applied++
        } catch (error) {
          failed++
          // Clean up failed git am operation
          try {
            execFileSync('git', ['am', '--abort'], { cwd: process.cwd() })
          } catch {
            // Ignore errors if there's nothing to abort
          }
          if (error instanceof Error && error.message.includes('conflict')) {
            conflicts.push(patch)
          }
        }
      }

      return { applied, failed, conflicts }
    }
  }
}
